#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    return;
}

define('COCOPI_CLI', true);

include_once(__DIR__."/cockpit/bootstrap.php");

if (isset($argv[1])) {

    $cmd = str_replace('../', '', $argv[1]);

    switch($cmd) {

        case 'test':
            CLI::writeln("Yepp!", true);
            break;
        default:

            if (file_exists(CP_SITE_DIR."/cli/{$cmd}.php")) {
                include(CP_SITE_DIR."/cli/{$cmd}.php");
            } else {
                CLI::writeln("Command - {$cmd} - not found!", false);
            }
    }
}