<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Error 500</title>
    <style type="text/css">

    * { box-sizing: border-box; }

    body {
        font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, "Lucida Grande", sans-serif;
        font-size: 18px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.4em;
        padding-top: 20px;
        color:black;
        background-color:#fff;
    }

    h1 { font-size:34px;letter-spacing: -2px;line-height: 1.2em;margin:0; }
    h2 { font-size:16px;font-weight:normal;color:#999; }
    h3 { font-weight:bold;font-size:11pt}
    p  { margin-top: 5px 0px;}

    .wrapper{
        width:940px;
        margin: 20px auto;
    }

    .error-message {
        margin: 20px 0;
        color: #1EAEDB;
    }

    .error-info {
        color: #666;
        font-size: 14px;
        line-height: 22px;
    }

    .italic {
        display: inline-block;
        margin-top: 10px;
        font-family: Georgia;
        padding: 5px 10px;
        border-radius: 2px;
        background: red;
        color: #fff;
    }

    .code {
        color: #666;
        background-color: #000;
        padding: 10px;
        font-size: 12px;
        border-radius: 4px;
    }

    .code ol {
        overflow-x: scroll;
    }

    .code li.selected {
        background: #333;
        color: yellow;
    }

    .version {
        margin-top: 20px;
        color: gray;
        font-size: 8pt;
    }
    </style>
</head>
<body>

    <div class="wrapper">
        <h1>Uuups - System Error</h1>

        <div class="error-message">
            <?php echo nl2br($error['message']); ?>
        </div>

    </div>
    <div class="wrapper content">

            <p class="error-info">
                <strong><?php echo str_replace(CP_ROOT_DIR,'',$error["file"]);?></strong>
                <br>
                <span class="italic">&mdash; on line <?php echo $error["line"];?></span>
            </p>

            <?php $lineoffset = 6; ?>

            <div class="code"><pre><ol start="<?php echo ($error["line"] - $lineoffset); ?>"><?php

                $line   = $error["line"]-1;
                $file   = file($error["file"]);

                if($line) {

                    $i = $lineoffset;

                    while(true){

                        if(isset($file[($line-$i)])){
                            echo '<li>'.htmlentities($file[($line-$i)]).'</li>';
                        }

                        $i--;

                        if($i==0) break;
                    }
                }

                echo '<li class="selected">'.htmlentities($file[$line]).'</li>';

                $i = 1;

                while(true){
                    if(!isset($file[($line+$i)]) || $i>$lineoffset) break;
                    echo '<li>'.htmlentities($file[($line+$i)]).'</li>';
                    $i++;
                }
            ?></ol></pre></div>

        <div class="version">
            System message generated by Copilot debug
        </div>
    </div>
</body>
</html>