<?php

$_COPILOT_SITE_DIR  = dirname(__DIR__);

define('COCKPIT_SITE_DIR', $_COPILOT_SITE_DIR);
define('COCKPIT_CONFIG_DIR', $_COPILOT_SITE_DIR.'/config');
define('COCKPIT_STORAGE_FOLDER' , $_COPILOT_SITE_DIR.'/storage');
define('COCKPIT_PUBLIC_STORAGE_FOLDER' , $_COPILOT_SITE_DIR.'/storage');
